#!/usr/bin/env python3
import helpers, sys, os
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @handle")

    #Query twitter
    x = helpers.get_user_timeline(sys.argv[1], count=50)
    
    #init analyzer
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    for tweet in x:
        score = analyzer.analyze(tweet)
        if score > 0:
            print(colored(":) {} {}".format(score, tweet), "green"))
        elif score < 0:
            print(colored(":( {} {}".format(score, tweet), "red"))
        else:
            print(colored(":| {} {}".format(score, tweet), "yellow"))
    # analyze word
    #score = analyzer.analyze(sys.argv[1])
#    if score > 0.0:
#        print(colored(":)", "green"))
 #   elif score < 0.0:
  #      print(colored(":(", "red"))
  #  else:
  #      print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()
